django/form/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'), # NEW(GET), CREATE(POST)
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'), # EDIT(GET), UPDATE(POST)
    path('<int:pk>/delete/', views.delete, name='delete'),
]

django/form/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

django/form/articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

django/form/articles/forms.py
from django import forms


class ArticleForm(forms.Form):
    title = forms.CharField(max_length=10)
    content = forms.CharField(max_length=150, widget=forms.Textarea)
# from django import forms
# from .models import Article


# # class ArticleForm(forms.Form):
# #     REGION_A = 'seoul'
# #     REGION_B = 'deajeon'
# #     REGIONS = [
# #         (REGION_A, '서울'),
# #         (REGION_B, '대전'),
# #     ]


# #     title = forms.CharField(max_length=10)
# #     content = forms.CharField(widget=forms.Textarea)
# #     region = forms.ChoiceField(choices=REGIONS, widget=forms.RadioSelect)

# class ArticleForm(forms.ModelForm):
#     title = forms.CharField(
#         label='제목',
#         widget=forms.TextInput(attrs={
#             'class': 'my-title form-control',
#             'placeholder': 'Enter the title',
#             'maxlength': 10,
#         })
#     )
#     content = forms.CharField(
#         label='내용',
#         widget=forms.Textarea(attrs={
#             'class': 'my-content form-control',
#             'rows': 5,
#             'cols': 50,
#         }),
#         error_messages={
#             'required': '내용 넣어라...'
#         }
#     )

#     class Meta:
#         model = Article
#         fields = '__all__'

django/form/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm

# Create your views here.
def index(request):
    # articles = Article.objects.all()
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


def new(request):
    form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/new.html', context)


def create(request):
    title = request.POST.get('title') 
    content = request.POST.get('content')
    article = Article(title=title, content=content)
    article.save()
    return redirect('articles:detail', article.pk)


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)


def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        return redirect('articles:detail', article.pk)


def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/edit.html', context)


def update(request, pk):
    article = Article.objects.get(pk=pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('articles:detail', article.pk)



# from django.shortcuts import render, redirect
# from django.views.decorators.http import require_http_methods, require_POST
# from .models import Article
# from .forms import ArticleForm

# # Create your views here.
# def index(request):
#     # articles = Article.objects.all()
#     articles = Article.objects.order_by('-pk')
#     context = {
#         'articles': articles,
#     }
#     return render(request, 'articles/index.html', context)


# @require_http_methods(['GET', 'POST'])
# def create(request):
#     # http method가 POST 일때
#     if request.method == 'POST':
#         form = ArticleForm(request.POST, request.FILES)
#         # 유효성 검증
#         if form.is_valid():
#             article = form.save()
#             return redirect('articles:detail', article.pk)
#     # GET (http method가 POST가 아닌 다른 method일 때)
#     else: 
#         form = ArticleForm()
#     context = {
#         # 1. is_valid에서 내려온 form : 에러메세지를 포함
#         # 2. else 구문에서 내려온 form
#         'form': form,
#     }
#     return render(request, 'articles/create.html', context)


# def detail(request, pk):
#     article = Article.objects.get(pk=pk)
#     context = {
#         'article': article,
#     }
#     return render(request, 'articles/detail.html', context)


# @require_http_methods(['GET', 'POST'])
# def update(request, pk):
#     article = Article.objects.get(pk=pk)
#     if request.method == 'POST': # update
#         # Create a form to edit an existing Article, but use
#         # POST data to populate the form.
#         form = ArticleForm(request.POST, instance=article)
#         if form.is_valid():
#             form.save()
#             return redirect('articles:detail', article.pk)
#     else: # edit
#         # Creating a form to change an existing article.
#         form = ArticleForm(instance=article)
#     context = {
#         'form': form,
#         'article': article,
#     }
#     return render(request, 'articles/update.html', context)


# @require_POST
# def delete(request, pk):
#     article = Article.objects.get(pk=pk)
#     article.delete()
#     return redirect('articles:index')

django/form/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">CREATE</h1>
  <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">[back]</a>


  {% comment %} <hr>

  <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
      {{ form.title.errors }}
      {{ form.title.label_tag }}
      {{ form.title }}
    </div>
    <div>
      {{ form.content.errors }}
      {{ form.content.label_tag }}
      {{ form.content }}
    </div>
    <input type="submit">
  </form>


  <hr>


  <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      {% for field in form %}
        {{ field.errors }}
        {{ field.label_tag }}
        {{ field }}
      {% endfor %}
    </div>
    <input type="submit">
  </form> {% endcomment %}

{% endblock %}

django/form/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h2 class='text-center'>DETAIL</h2>
  <h3>{{ article.pk }} 번째 글</h3>
  {% if article.image %}
    <img src="{{ article.image.url }}" alt="{{ article.image }}">
  {% endif %}
  <hr>
  <p>제목: {{ article.title }}</p>
  <p>내용: {{ article.content }}</p>
  <p>작성 시각: {{ article.created_at|date:"SHORT_DATE_FORMAT" }}</p>
  <p>수정 시각: {{ article.updated_at|date:"M j, Y" }}</p>
  <hr>
  <a href="{% url 'articles:update' article.pk %}">[UPDATE]</a><br>
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>
  <a href="{% url 'articles:index' %}">[back]</a>
{% endblock  %}

django/form/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'stylesheets/style.css' %}">
{% endblock %}

{% block content %}
  <img src="{% static 'articles/images/sample.jpg' %}" alt="sample img">
  <h1 class="text-center">Articles</h1>
  <a href="{% url 'articles:create' %}">NEW</a>
  <hr>
  {% for article in articles %}
    <p>글 번호: {{ article.pk }}</p>
    <p>글 제목: {{ article.title }}</p>
    <p>글 내용: {{ article.content }}</p>
    <a href="{% url 'articles:detail' article.pk %}">[detail]</a>
    <hr>
  {% endfor %}
{% endblock %}

django/form/articles/templates/articles/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <h1 class="text-center">UPDATE</h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
  </form>
  <hr>
  <a href="{% url 'articles:detail' article.pk %}">[back]</a>
{% endblock %}

django/form/crud/templates/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  {% bootstrap_css %}
  {% block css %}{% endblock %}
</head>
<body>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  {% bootstrap_javascript jquery='full' %}
</body>
</html>